#!/bin/bash

ZIP=zip
TMPOUT=$(mktemp -u -t ioio).zip
PROJECTS="IOIOLib \
          IOIOLibBT \
          applications/HelloIOIO \
          applications/HelloIOIOPower \
          applications/IOIOSimpleApp"

TARGETS=(android-3 \
         android-10 \
         android-7 \
         android-7 \
         android-7)

APKS="applications/HelloIOIO \
      applications/HelloIOIOPower \
      applications/IOIOSimpleApp"

if test $# -ne 1; then
  echo "Usage: $0 <out_zip>"
  exit 1
fi

cd software

i=0
for PROJECT in $PROJECTS; do
  (cd $PROJECT && android -s update project --name $(basename $PROJECT) --path . --target ${TARGETS[i]})
  let "i++"
done

echo Generating Javadoc for IOIOLib
ant -q -f IOIOLib/javadoc.xml

for PROJECT in $PROJECTS; do
  echo SOURCE: $PROJECT
  $ZIP -q -r $TMPOUT $PROJECT -x "$PROJECT/bin/*" "$PROJECT/gen/*"
done

for APK in $APKS; do
  echo BINARY: $APK
  (cd $APK && ant -q debug >/dev/null)
  BASENAME=$(basename $APK)
  APK_DEBUG="$APK/bin/$BASENAME-debug.apk"
  APK="$APK/bin/$BASENAME.apk"
  mv $APK_DEBUG $APK
  $ZIP -q -j $TMPOUT $APK
done

cd -
mv $TMPOUT $1
