#!/bin/bash

PROJECTS="libusb libconn libbtstack libadb libsdcard bootloader device_bootloader app_layer_v1 blink latency_tester"

if [[ -z "$MAKE" ]] && which colormake > /dev/null 2>&1 ; then
   MAKE=colormake
else
   MAKE=make     
fi

for PROJ in $PROJECTS; do
  echo ===========================================
  echo $PROJ
  echo ===========================================
  if ! prjMakefilesGenerator.bat firmware/$PROJ; then echo "WARNING: failed to regenerate Makefiles."; fi
  if ! $MAKE -C firmware/$PROJ "$@"; then echo FAILURE ; exit 1 ; fi
done
echo SUCCESS

