#!/bin/bash

if test $# -ne 1; then
  echo "Usage: $0 <out_zip>"
  exit 1
fi

if [ $(uname -o) = Cygwin ]; then
  ANDROID='cmd /C android'
else
  ANDROID=android
fi

ZIP=zip
TMPOUT=$(mktemp -ut ioio.XXXXXX.zip)

LIBPROJECTS="IOIOLib/target/android \
             IOIOLibBT \
             IOIOLibAccessory \
             IOIOLibAndroidDevice"

APPPROJECTS="applications/HelloIOIO \
             applications/HelloIOIOService \
             applications/IOIOSimpleApp"

APKS="applications/HelloIOIO \
      applications/HelloIOIOService \
      applications/IOIOSimpleApp"

SOURCEDIRS="IOIOLib \
            IOIOLibBT \
            IOIOLibAccessory \
            applications/HelloIOIO \
            applications/HelloIOIOService \
            applications/IOIOSimpleApp \
            applications/pc/HelloIOIOConsole \
            applications/pc/HelloIOIOSwing \
            applications/pc/HelloSequencer"

PCAPPS="applications/pc/HelloIOIOConsole \
        applications/pc/HelloIOIOSwing"

cd software

echo =====================================================
echo WARNING: THE FOLLOWING FILES ARE ABOUT TO BE DELETED:
echo =====================================================
git clean -xdn
read -p "Enter to confirm, or ^c to abort..."
git clean -xdf

echo =================
echo Packaging sources
echo =================
for DIR in $SOURCEDIRS; do
  echo SOURCE: $DIR
  $ZIP -q -r $TMPOUT $DIR || exit 1
done

echo =================================
echo Updating Android library projects
echo =================================
i=0
for PROJECT in $LIBPROJECTS; do
  $ANDROID update lib-project -p $PROJECT  || exit 1
  ant -f $PROJECT/build.xml clean || exit 1
  let "i++"
done

echo =====================================
echo Updating Android application projects
echo =====================================
i=0
for PROJECT in $APPPROJECTS; do
  $ANDROID update project -p $PROJECT || exit 1
  ant -f $PROJECT/build.xml clean || exit 1
  let "i++"
done


echo ==============================
echo Generating Javadoc for IOIOLib
echo ==============================
ant -q -f IOIOLib/javadoc.xml || exit 1

echo ============================================================
echo Building Android application projects and packaging binaries
echo ============================================================
i=0
for PROJECT in $APPPROJECTS; do
  APPNAME=$(basename $PROJECT)
  ant -f $PROJECT/build.xml debug || exit 1
  mv $PROJECT/bin/$APPNAME{-debug,}.apk || exit 1
  $ZIP -q -j $TMPOUT $PROJECT/bin/$APPNAME.apk || exit 1
  let "i++"
done

echo =============================
echo Packaging PC application JARs
echo =============================
for APP in $PCAPPS; do
  NAME=$(basename $APP)
  ant -f $APP/build.xml jar
  $ZIP -q -j $TMPOUT $APP/jar/$NAME.jar || exit 1
done

cd -
mv $TMPOUT $1 || exit 1
