#!/bin/bash

PROJECTS="libusb libconn libbtstack libadb bootloader app_layer_v1 blink latency_tester"

if [[ -z "$MAKE" ]] && which colormake > /dev/null 2>&1 ; then
   MAKE=colormake
else
   MAKE=make     
fi
for PROJ in $PROJECTS; do
  echo ===========================================
  echo $PROJ
  echo ===========================================
  $MAKE -C firmware/$PROJ "$@"
done

